// Source generator: SerilogArityGenerator
// Emits Serilog-hole-named typed overloads for SerilogLoggerAdapter.
//
// Key distinction vs TypedArgsOverloadGenerator:
//   TypedArgsOverloadGenerator names from [CallerArgumentExpression] (arg source text).
//   THIS generator names from template holes via SerilogTemplateHoleIndex.NameAt.
//   For Log.Information("User {Id} ordered {@Order}", userId, order):
//     hole 0 = "Id", hole 1 = "Order" -- NOT "userId"/"order".
//
// Every hole rides the zero-alloc compact buffer; the per-hole capture mode
// ({@} = Destructure, {$} = Stringify, bare = Default) is packed into the
// LogPropertyCompact slot via HoleEntry.CaptureModeAt. No fast/slow branch.
// Resolve-once: ResolveEntry does 1 dictionary lookup; NameAt/CaptureModeAt
// on the returned HoleEntry are plain array reads (no further lookup).
//
// Identity gate: only emits for MMP.Herald.Serilog compilation.
#nullable enable
using System.Text;
using Microsoft.CodeAnalysis;
namespace MMP.Herald.Generators;
[Generator]
public sealed class SerilogArityGenerator : IIncrementalGenerator
{
    private const int MaxArity = 16;
    // Six Serilog levels -- includes Fatal which the native generator omits.
    private static readonly string[] Levels =
    {
        "Verbose", "Debug", "Information", "Warning", "Error", "Fatal",
    };
    // Delegate to the shared helper (DRY with TypedArgsOverloadGenerator).
    private static int BufferSizeFor(int arity) => GeneratorArityHelpers.BufferSizeFor(arity);
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Identity gate: only emit when SerilogLoggerAdapter is declared in THIS compilation.
        var trigger = context.CompilationProvider.Select(static (c, _) =>
        {
            var marker = c.GetTypeByMetadataName("MMP.Herald.Serilog.SerilogLoggerAdapter");
            return marker is not null
                && SymbolEqualityComparer.Default.Equals(marker.ContainingAssembly, c.Assembly);
        });
        context.RegisterSourceOutput(trigger, static (ctx, isCompat) =>
        {
            if (!isCompat) return;
            var sb = new StringBuilder(128 * 1024);
            BuildFile(sb);
            ctx.AddSource("SerilogLoggerAdapter.Holes.Generated.cs", sb.ToString());
        });

        // Gate 2: Layer-2 compilation (Serilog assembly declaring Serilog.Core.Logger).
        // Emits typed overloads for Core.Logger and typed static methods for Serilog.Log
        // so that Serilog.Log.Information(tmpl, a, b) routes to the zero-alloc kernel.
        var layer2Trigger = context.CompilationProvider.Select(static (c, _) =>
        {
            var marker = c.GetTypeByMetadataName("Serilog.Core.Logger");
            return marker is not null
                && SymbolEqualityComparer.Default.Equals(marker.ContainingAssembly, c.Assembly);
        });
        context.RegisterSourceOutput(layer2Trigger, static (ctx, isLayer2) =>
        {
            if (!isLayer2) return;
            var sbLogger = new StringBuilder(64 * 1024);
            BuildLayer2LoggerFile(sbLogger);
            ctx.AddSource("Layer2Logger.Holes.Generated.cs", sbLogger.ToString());
            var sbLog = new StringBuilder(64 * 1024);
            BuildLayer2LogFile(sbLog);
            ctx.AddSource("Layer2Log.Holes.Generated.cs", sbLog.ToString());
        });
    }
    private static void BuildFile(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Generated by MMP.Herald.Generators.SerilogArityGenerator.");
        sb.AppendLine("// Do not edit by hand.");
        sb.AppendLine("// Serilog naming rule: hole names from MESSAGE TEMPLATE, not CallerArgumentExpression.");
        sb.AppendLine("// ResolveEntry returns a HoleEntry (1 lookup); NameAt/CaptureModeAt read arrays directly (no further lookup).");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using MMP.Herald.Events;");
        sb.AppendLine("using MMP.Herald.Levels;");
        sb.AppendLine("using MMP.Herald.Pipeline.Kernel;");
        sb.AppendLine();
        sb.AppendLine("namespace MMP.Herald.Serilog;");
        sb.AppendLine();
        sb.AppendLine("public sealed partial class SerilogLoggerAdapter");
        sb.AppendLine("{");
        foreach (var level in Levels)
        {
            sb.Append("    // ").Append(level).AppendLine(" hole-named typed overloads 1..16");
            sb.AppendLine();
            for (var arity = 1; arity <= MaxArity; arity++)
                EmitOverload(sb, level, arity);
        }
        sb.AppendLine("}");
    }
    private static void EmitOverload(StringBuilder sb, string level, int arity)
    {
        var typeArgs    = BuildTypeArgs(arity);
        var valueParams = BuildValueParams(arity);
        var bufferSize  = BufferSizeFor(arity);
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.Append("    [OverloadResolutionPriority(").Append(arity).AppendLine(")]");
        sb.Append("    public void ").Append(level).Append("<").Append(typeArgs)
          .Append(">(string messageTemplate, ").Append(valueParams).AppendLine(")");
        sb.AppendLine("    {");
        sb.Append("        if (!_herald.Is").Append(level).AppendLine("Acceptable) return;");
        sb.AppendLine();
        // Resolve-once: one dictionary lookup, then 2N plain array reads.
        // Previously: 2N lookups (NameAt + CaptureModeAt each did a TryGetValue).
        sb.AppendLine("        var _entry = global::MMP.Herald.Serilog.SerilogTemplateHoleIndex.Instance.ResolveEntry(messageTemplate);");
        sb.AppendLine();
        // Every hole rides the compact buffer; the per-hole capture mode is
        // packed into the LogPropertyCompact slot. No fast/slow branch — a
        // {@}/{$} hole carries Destructure/Stringify in the slot.
        sb.Append("        var _buf = new global::MMP.Herald.Pipeline.Kernel.LogPropertyBuffer")
          .Append(bufferSize).AppendLine("();");
        for (var i = 0; i < arity; i++)
        {
            sb.Append("        _buf[").Append(i)
              .Append("] = global::MMP.Herald.Pipeline.Kernel.LogPropertyCompact.From(")
              .AppendLine();
            sb.Append("            _entry.NameAt(").Append(i)
              .Append("), v").Append(i + 1).Append(",").AppendLine();
            sb.Append("            _entry.CaptureModeAt(").Append(i).AppendLine("));");
        }
        sb.Append("        System.ReadOnlySpan<global::MMP.Herald.Pipeline.Kernel.LogPropertyCompact> _span = ")
          .Append("((System.Span<global::MMP.Herald.Pipeline.Kernel.LogPropertyCompact>)_buf).Slice(0, ")
          .Append(arity).AppendLine(");");
        sb.Append("        _herald.LogCompact(global::MMP.Herald.Levels.KnownLogLevels.")
          .Append(level).AppendLine(",");
        sb.AppendLine("            global::MMP.Herald.Events.LogCategory.None, messageTemplate, _span);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }
    private static string BuildTypeArgs(int n)
    {
        var sb = new StringBuilder(n * 4);
        for (var i = 1; i <= n; i++) { if (i > 1) sb.Append(", "); sb.Append("T").Append(i); }
        return sb.ToString();
    }
    private static string BuildValueParams(int n)
    {
        var sb = new StringBuilder(n * 8);
        for (var i = 1; i <= n; i++) { if (i > 1) sb.Append(", "); sb.Append("T").Append(i).Append(" v").Append(i); }
        return sb.ToString();
    }
    // Layer-2 Core.Logger partial -- typed overloads (one-line forwards to _adapter).
    // DRY: the compact-buffer logic lives only in SerilogLoggerAdapter, not duplicated here.
    private static void BuildLayer2LoggerFile(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Generated by MMP.Herald.Generators.SerilogArityGenerator (Layer-2 gate).");
        sb.AppendLine("// Do not edit by hand.");
        sb.AppendLine("// Typed overloads on Serilog.Core.Logger delegate to _adapter");
        sb.AppendLine("// (MMP.Herald.Serilog.SerilogLoggerAdapter) which carries the zero-alloc path.");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("namespace Serilog.Core;");
        sb.AppendLine();
        sb.AppendLine("public sealed partial class Logger");
        sb.AppendLine("{");
        foreach (var level in Levels)
        {
            sb.Append("    // ").Append(level).AppendLine(" typed overloads 1..16 -- one-line forwards to _adapter");
            sb.AppendLine();
            for (var arity = 1; arity <= MaxArity; arity++)
                EmitLayer2LoggerOverload(sb, level, arity);
        }
        sb.AppendLine("}");
    }
    private static void EmitLayer2LoggerOverload(StringBuilder sb, string level, int arity)
    {
        var typeArgs    = BuildTypeArgs(arity);
        var valueParams = BuildValueParams(arity);
        var valueArgs   = BuildValueArgs(arity);
        var paramsArgs  = BuildParamsArgs(arity);
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.Append("    [OverloadResolutionPriority(").Append(arity).AppendLine(")]");
        sb.Append("    public void ").Append(level).Append("<").Append(typeArgs)
          .Append(">(string messageTemplate, ").Append(valueParams).AppendLine(")");
        sb.AppendLine("    {");
        sb.AppendLine("        // Fast path: concrete adapter available (most cases).");
        sb.AppendLine("        if (_adapter is { } a)");
        sb.Append("        { a.").Append(level).Append("(messageTemplate, ").Append(valueArgs).AppendLine("); return; }");
        sb.AppendLine("        // Fallback: SilentLogger or non-adapter slot -- params-object verb.");
        sb.Append("        _inner.").Append(level).Append("(messageTemplate, ").Append(paramsArgs).AppendLine(");");
        sb.AppendLine("    }");
        sb.AppendLine();
    }
    // Layer-2 Serilog.Log partial -- typed static methods.
    // [OverloadResolutionPriority] wins over params object[] at the call site.
    // Pattern-matches L1.Log.Logger to SerilogLoggerAdapter; falls through to
    // the params verb for SilentLogger or any non-adapter logger.
    private static void BuildLayer2LogFile(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Generated by MMP.Herald.Generators.SerilogArityGenerator (Layer-2 gate).");
        sb.AppendLine("// Do not edit by hand.");
        sb.AppendLine("// Typed static methods on Serilog.Log route to the zero-alloc kernel");
        sb.AppendLine("// when the ambient logger is a SerilogLoggerAdapter.");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("namespace Serilog;");
        sb.AppendLine();
        sb.AppendLine("public static partial class Log");
        sb.AppendLine("{");
        foreach (var level in Levels)
        {
            sb.Append("    // ").Append(level).AppendLine(" typed static overloads 1..16");
            sb.AppendLine();
            for (var arity = 1; arity <= MaxArity; arity++)
                EmitLayer2LogOverload(sb, level, arity);
        }
        sb.AppendLine("}");
    }
    private static void EmitLayer2LogOverload(StringBuilder sb, string level, int arity)
    {
        var typeArgs    = BuildTypeArgs(arity);
        var valueParams = BuildValueParams(arity);
        var valueArgs   = BuildValueArgs(arity);
        var paramsArgs  = BuildParamsArgs(arity);
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.Append("    [OverloadResolutionPriority(").Append(arity).AppendLine(")]");
        sb.Append("    public static void ").Append(level).Append("<").Append(typeArgs)
          .Append(">(string messageTemplate, ").Append(valueParams).AppendLine(")");
        sb.AppendLine("    {");
        sb.AppendLine("        // Fast path: typed overload on the concrete SerilogLoggerAdapter.");
        sb.AppendLine("        if (global::MMP.Herald.Serilog.Log.Logger is global::MMP.Herald.Serilog.SerilogLoggerAdapter _a)");
        sb.Append("        { _a.").Append(level).Append("(messageTemplate, ").Append(valueArgs).AppendLine("); return; }");
        sb.AppendLine("        // Fallback: SilentLogger or non-adapter -- use params-object verb.");
        sb.Append("        global::MMP.Herald.Serilog.Log.").Append(level)
          .Append("(messageTemplate, ").Append(paramsArgs).AppendLine(");");
        sb.AppendLine("    }");
        sb.AppendLine();
    }
    private static string BuildValueArgs(int n)
    {
        var sb = new StringBuilder(n * 4);
        for (var i = 1; i <= n; i++) { if (i > 1) sb.Append(", "); sb.Append("v").Append(i); }
        return sb.ToString();
    }
    private static string BuildParamsArgs(int n)
    {
        var sb = new StringBuilder(n * 12);
        for (var i = 1; i <= n; i++) { if (i > 1) sb.Append(", "); sb.Append("(object?)v").Append(i); }
        return sb.ToString();
    }
}
