// Source generator: SerilogArityGenerator
// Emits Serilog-hole-named typed overloads for SerilogLoggerAdapter.
//
// Key distinction vs TypedArgsOverloadGenerator:
//   TypedArgsOverloadGenerator names from [CallerArgumentExpression] (arg source text).
//   THIS generator names from template holes via SerilogTemplateHoleIndex.NameAt.
//   For Log.Information("User {Id} ordered {@Order}", userId, order):
//     hole 0 = "Id", hole 1 = "Order" -- NOT "userId"/"order".
//
// All-default-mode holes (bare {Name}): compact buffer fast path.
// Any non-default hole ({@} or {$}): fall through to params-object slow path.
//
// Identity gate: only emits for MMP.Herald.Serilog compilation.
#nullable enable
using System.Text;
using Microsoft.CodeAnalysis;
namespace MMP.Herald.Generators;
[Generator]
public sealed class SerilogArityGenerator : IIncrementalGenerator
{
    private const int MaxArity = 16;
    // Six Serilog levels -- includes Fatal which the native generator omits.
    private static readonly string[] Levels =
    {
        "Verbose", "Debug", "Information", "Warning", "Error", "Fatal",
    };
    // Delegate to the shared helper (DRY with TypedArgsOverloadGenerator).
    private static int BufferSizeFor(int arity) => GeneratorArityHelpers.BufferSizeFor(arity);
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Identity gate: only emit when SerilogLoggerAdapter is declared in THIS compilation.
        var trigger = context.CompilationProvider.Select(static (c, _) =>
        {
            var marker = c.GetTypeByMetadataName("MMP.Herald.Serilog.SerilogLoggerAdapter");
            return marker is not null
                && SymbolEqualityComparer.Default.Equals(marker.ContainingAssembly, c.Assembly);
        });
        context.RegisterSourceOutput(trigger, static (ctx, isCompat) =>
        {
            if (!isCompat) return;
            var sb = new StringBuilder(128 * 1024);
            BuildFile(sb);
            ctx.AddSource("SerilogLoggerAdapter.Holes.Generated.cs", sb.ToString());
        });
    }
    private static void BuildFile(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Generated by MMP.Herald.Generators.SerilogArityGenerator.");
        sb.AppendLine("// Do not edit by hand.");
        sb.AppendLine("// Serilog naming rule: hole names from MESSAGE TEMPLATE, not CallerArgumentExpression.");
        sb.AppendLine("// SerilogTemplateHoleIndex.NameAt resolves positionally after a single parse per template.");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using MMP.Herald.Events;");
        sb.AppendLine("using MMP.Herald.Levels;");
        sb.AppendLine("using MMP.Herald.Pipeline.Kernel;");
        sb.AppendLine();
        sb.AppendLine("namespace MMP.Herald.Serilog;");
        sb.AppendLine();
        sb.AppendLine("public sealed partial class SerilogLoggerAdapter");
        sb.AppendLine("{");
        foreach (var level in Levels)
        {
            sb.Append("    // ").Append(level).AppendLine(" hole-named typed overloads 1..16");
            sb.AppendLine();
            for (var arity = 1; arity <= MaxArity; arity++)
                EmitOverload(sb, level, arity);
        }
        sb.AppendLine("}");
    }
    private static void EmitOverload(StringBuilder sb, string level, int arity)
    {
        var typeArgs    = BuildTypeArgs(arity);
        var valueParams = BuildValueParams(arity);
        var bufferSize  = BufferSizeFor(arity);
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.Append("    [OverloadResolutionPriority(").Append(arity).AppendLine(")]");
        sb.Append("    public void ").Append(level).Append("<").Append(typeArgs)
          .Append(">(string messageTemplate, ").Append(valueParams).AppendLine(")");
        sb.AppendLine("    {");
        sb.Append("        if (!_herald.Is").Append(level).AppendLine("Acceptable) return;");
        sb.AppendLine();
        sb.AppendLine("        var _holeIndex = global::MMP.Herald.Serilog.SerilogTemplateHoleIndex.Instance;");
        sb.AppendLine();
        sb.Append("        if (");
        for (var i = 0; i < arity; i++)
        {
            if (i > 0) { sb.AppendLine(); sb.Append("            && "); }
            sb.Append("_holeIndex.IsDefaultModeAt(messageTemplate, ").Append(i).Append(")");
        }
        sb.AppendLine(")");
        sb.AppendLine("        {");
        sb.AppendLine("            // Fast path: all holes default-mode -> zero-alloc compact buffer.");
        sb.Append("            var _buf = new global::MMP.Herald.Pipeline.Kernel.LogPropertyBuffer")
          .Append(bufferSize).AppendLine("();");
        for (var i = 0; i < arity; i++)
        {
            sb.Append("            _buf[").Append(i)
              .Append("] = global::MMP.Herald.Pipeline.Kernel.LogPropertyCompact.From(")
              .Append("_holeIndex.NameAt(messageTemplate, ").Append(i)
              .Append("), v").Append(i + 1).AppendLine(");");
        }
        sb.Append("            System.ReadOnlySpan<global::MMP.Herald.Pipeline.Kernel.LogPropertyCompact> _span = ")
          .Append("((System.Span<global::MMP.Herald.Pipeline.Kernel.LogPropertyCompact>)_buf).Slice(0, ")
          .Append(arity).AppendLine(");");
        sb.Append("            _herald.LogCompact(global::MMP.Herald.Levels.KnownLogLevels.")
          .Append(level).AppendLine(",");
        sb.AppendLine("                global::MMP.Herald.Events.LogCategory.None, messageTemplate, _span);");
        sb.AppendLine("            return;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        // Slow path: non-default capture mode.");
        sb.AppendLine("        // Delegate to params-object verb; WriteCore reads capture mode from parsed tokens.");
        sb.Append("        this.").Append(level).Append("(messageTemplate");
        for (var i = 1; i <= arity; i++)
            sb.Append(", (object?)v").Append(i);
        sb.AppendLine(");");
        sb.AppendLine("    }");
        sb.AppendLine();
    }
    private static string BuildTypeArgs(int n)
    {
        var sb = new StringBuilder(n * 4);
        for (var i = 1; i <= n; i++) { if (i > 1) sb.Append(", "); sb.Append("T").Append(i); }
        return sb.ToString();
    }
    private static string BuildValueParams(int n)
    {
        var sb = new StringBuilder(n * 8);
        for (var i = 1; i <= n; i++) { if (i > 1) sb.Append(", "); sb.Append("T").Append(i).Append(" v").Append(i); }
        return sb.ToString();
    }
}
