// Source generator that emits a [ModuleInitializer] hook in every
// Herald.Sinks.* assembly. The hook auto-registers each ILogSinkProvider
// the assembly contains into LogSinkProviderRegistry.Default at assembly
// load time, so a `dotnet add package MMP.Herald.Sinks.X` is the whole
// developer workflow — no fluent WithXSinkProviders() call, no manual
// RegisterAll(registry), no reflection-based scan.
//
// Why a generator instead of reflection:
//
//   The existing PluginLoader.ScanDefaultContext path walks every loaded
//   assembly with `assembly.GetTypes()` and looks for ILogSinkProvider
//   implementations. That works but (1) it's AOT-hostile because of the
//   reflection metadata it requires, and (2) it only runs when the host
//   calls `app.UseHeraldPlugins(...)`, so plain QuickLogBuilder users
//   never get auto-discovery. A source generator emitting compile-time
//   `new T()` calls is AOT-clean and runs at module init for every host.
//
// What the generator emits (per sink assembly):
//
//   <auto-generated>
//   using System.Runtime.CompilerServices;
//   using MMP.Herald.Routing;
//
//   namespace Herald.Sinks.File.__Generated__;
//
//   internal static class __SinkAutoRegistration__
//   {
//       [ModuleInitializer]
//       internal static void Register()
//       {
//           LogSinkProviderRegistry.Default.Register(
//               new global::Herald.Sinks.File.Providers.TextFileSinkProvider());
//           LogSinkProviderRegistry.Default.Register(
//               new global::Herald.Sinks.File.Providers.JsonFileSinkProvider());
//       }
//   }
//
// Detection rules:
//
//   A class T is emitted by the generator iff ALL of the following hold:
//     1. T is `public` and `class` (records work too — they are classes).
//     2. T is not `abstract`, not `static`, not generic, not nested.
//     3. T transitively implements `MMP.Herald.Routing.ILogSinkProvider`.
//     4. T has at least one public constructor whose parameters are ALL
//        optional (have a default value). The generator picks the
//        no-arg or all-defaulted ctor and calls `new T()` — every
//        omitted argument takes its declared default.
//     5. T does not carry `[NoAutoRegister]` (a per-type opt-out attribute
//        consumers can apply when they ship a provider that needs explicit
//        configuration before it can be used; the generator skips those).
//
// Assemblies the generator skips entirely:
//
//   * MMP.Herald.Core itself — Core contains no sink providers and a self-
//     registering hook would introduce a circular load-order concern.
//   * Any assembly that does not reference the ILogSinkProvider type
//     symbol at all — the generator early-outs in those compilations.
//
// AOT story:
//
//   The emitted file is plain C# the ILC analyzer treats identically to
//   hand-written code. `new T()` is a static instantiation the linker
//   can trace; no MakeGenericType, no Type.GetType, no Activator. The
//   [ModuleInitializer] runs once per assembly load on any runtime that
//   supports the attribute (.NET 5+). Herald targets net8.0;net9.0;net10.0,
//   so the attribute is always available.

#nullable enable

using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace MMP.Herald.Generators;

[Generator]
public sealed class SinkAutoRegistrationGenerator : IIncrementalGenerator
{
    private const string ILogSinkProviderFullName = "MMP.Herald.Routing.ILogSinkProvider";
    private const string NoAutoRegisterAttributeFullName = "MMP.Herald.Routing.NoAutoRegisterAttribute";
    private const string CoreAssemblyName = "MMP.Herald.Core";
    private const string CoreObfuscatedAssemblyName = "Herald.Core-Enterprise";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Collect every concrete public type-symbol that survives the
        // sink-shape filter. IsCandidateClass is a syntactic prefilter
        // (cheap) — semantic-model checks (HasInterface, ctor probing)
        // happen in the symbol step.
        var providerTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidateClassSyntax(node),
                transform: static (ctx, _) => TryGetProviderSymbol(ctx))
            .Where(static sym => sym is not null)
            .Select(static (sym, _) => sym!);

        // Combine all matched providers with the compilation so we can
        // (a) emit a single registration file per assembly, (b) read the
        // assembly name for the namespace fragment.
        var collected = providerTypes.Collect()
            .Combine(context.CompilationProvider);

        context.RegisterSourceOutput(collected, static (spc, tuple) =>
        {
            var (providers, compilation) = tuple;
            if (providers.IsDefaultOrEmpty) return;

            // Skip Core's own compilation. A Core sink provider would be
            // unusual; the safe default is to keep Core out of the
            // auto-register pipeline so the load order stays predictable.
            var assemblyName = compilation.AssemblyName ?? string.Empty;
            if (assemblyName == CoreAssemblyName ||
                assemblyName == CoreObfuscatedAssemblyName)
            {
                return;
            }

            // De-dup across partial-class declarations: types are equal by
            // SymbolEqualityComparer, but the syntax-provider yields one
            // result per declaration site for partials.
            var distinct = providers
                .Distinct(SymbolEqualityComparer.Default)
                .OfType<INamedTypeSymbol>()
                .OrderBy(t => t.ToDisplayString(), System.StringComparer.Ordinal)
                .ToArray();
            if (distinct.Length == 0) return;

            var source = EmitRegistrationSource(assemblyName, distinct);
            spc.AddSource("__SinkAutoRegistration__.g.cs", source);
        });
    }

    private static bool IsCandidateClassSyntax(SyntaxNode node)
    {
        // Cheap syntactic gate. The full filter is in TryGetProviderSymbol
        // which has the semantic model available.
        if (node is not Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax cls)
            return false;

        // Skip nested classes (a parent type-declaration ancestor is the
        // only way the SyntaxNode has a TypeDeclarationSyntax parent).
        if (cls.Parent is Microsoft.CodeAnalysis.CSharp.Syntax.TypeDeclarationSyntax)
            return false;

        // Skip abstract / static / generic at the syntactic level.
        if (cls.TypeParameterList is not null) return false;

        foreach (var modifier in cls.Modifiers)
        {
            var kind = modifier.Kind();
            if (kind == SyntaxKind.AbstractKeyword) return false;
            if (kind == SyntaxKind.StaticKeyword) return false;
        }

        // Require `public` accessor — sinks that want to ship a private
        // provider can opt back in by exposing it publicly; the auto-
        // registration story is for public surface only.
        var isPublic = false;
        foreach (var modifier in cls.Modifiers)
        {
            if (modifier.Kind() == SyntaxKind.PublicKeyword)
            {
                isPublic = true;
                break;
            }
        }
        return isPublic;
    }

    private static INamedTypeSymbol? TryGetProviderSymbol(GeneratorSyntaxContext ctx)
    {
        if (ctx.Node is not Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax decl)
            return null;

        if (ctx.SemanticModel.GetDeclaredSymbol(decl) is not INamedTypeSymbol sym)
            return null;

        // Belt-and-braces version of the syntactic checks at symbol level.
        if (sym.IsAbstract || sym.IsStatic || sym.IsGenericType) return null;
        if (sym.ContainingType is not null) return null; // nested
        if (sym.DeclaredAccessibility != Accessibility.Public) return null;

        // Must implement ILogSinkProvider (transitively).
        if (!ImplementsILogSinkProvider(sym)) return null;

        // Must carry a publicly-constructable ctor (no params OR every
        // param optional). Falling back through all public ctors lets a
        // sink keep advanced ctors for manual wiring while still being
        // auto-registerable through a defaulted one.
        if (!HasPubliclyConstructableCtor(sym)) return null;

        // [NoAutoRegister] escape hatch.
        if (HasNoAutoRegisterAttribute(sym)) return null;

        return sym;
    }

    private static bool ImplementsILogSinkProvider(INamedTypeSymbol sym)
    {
        foreach (var iface in sym.AllInterfaces)
        {
            if (iface.ToDisplayString() == ILogSinkProviderFullName) return true;
        }
        return false;
    }

    private static bool HasPubliclyConstructableCtor(INamedTypeSymbol sym)
    {
        foreach (var ctor in sym.InstanceConstructors)
        {
            if (ctor.DeclaredAccessibility != Accessibility.Public) continue;
            var allOptional = true;
            foreach (var p in ctor.Parameters)
            {
                if (!p.IsOptional && !p.HasExplicitDefaultValue)
                {
                    allOptional = false;
                    break;
                }
            }
            if (allOptional) return true;
        }
        return false;
    }

    private static bool HasNoAutoRegisterAttribute(INamedTypeSymbol sym)
    {
        foreach (var attr in sym.GetAttributes())
        {
            if (attr.AttributeClass?.ToDisplayString() == NoAutoRegisterAttributeFullName)
                return true;
        }
        return false;
    }

    private static string EmitRegistrationSource(string assemblyName, INamedTypeSymbol[] providers)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Generated by MMP.Herald.Generators.SinkAutoRegistrationGenerator.");
        sb.AppendLine("// Do not edit. Re-emitted on every build.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using MMP.Herald.Routing;");
        sb.AppendLine();

        // Per-assembly namespace fragment so two sink assemblies cannot
        // collide on the `__SinkAutoRegistration__` type name. Strip any
        // dots / dashes from the assembly name to keep the identifier valid.
        var ns = "__HeraldSinkAutoRegistration__." + SanitizeIdentifier(assemblyName);
        sb.Append("namespace ").Append(ns).AppendLine(";");
        sb.AppendLine();
        sb.AppendLine("internal static class __SinkAutoRegistration__");
        sb.AppendLine("{");
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    internal static void Register()");
        sb.AppendLine("    {");

        foreach (var provider in providers)
        {
            var fq = provider.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.Append("        LogSinkProviderRegistry.Default.Register(new ")
              .Append(fq)
              .AppendLine("());");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string SanitizeIdentifier(string name)
    {
        if (string.IsNullOrEmpty(name)) return "Anonymous";
        var sb = new StringBuilder(name.Length);
        foreach (var c in name)
        {
            sb.Append(char.IsLetterOrDigit(c) ? c : '_');
        }
        if (char.IsDigit(sb[0])) sb.Insert(0, '_');
        return sb.ToString();
    }
}
