#nullable enable

// Serilog.Core.Logger — the concrete type that corpus code stores:
//   Logger log = new LoggerConfiguration()....CreateLogger();
//
// Layer-1 LoggerConfiguration.CreateLogger() returns MMP.Herald.Serilog.ILogger
// (an interface). This class wraps that interface result so the Layer-2
// CreateLogger() can return a concrete Serilog.Core.Logger, matching the
// real Serilog API where Logger is a sealed class not an interface.
//
// It is a wrapper, not a cast — the Layer-1 result is stored in _inner
// and every ILogger member is forwarded through it.
//
// Interface type contract:
//   Serilog.ILogger (Layer-2, ILogger.cs) declares IsEnabled/Write using
//   MMP.Herald.Serilog.Events.LogEventLevel (the L1 type, aliased as L1Events).
//   Logger must implement those methods using the same L1 type.
//   Since _inner also uses L1Events.LogEventLevel, every forward is a straight
//   pass-through with no conversion required.

using System;
using System.Runtime.CompilerServices;
using L1 = MMP.Herald.Serilog;
using L1Events = MMP.Herald.Serilog.Events;

namespace Serilog.Core;

/// <summary>
/// The concrete logger type returned by <c>LoggerConfiguration.CreateLogger()</c>.
/// Wraps the Layer-1 <see cref="L1.ILogger"/> produced by
/// <c>MMP.Herald.Serilog.Configuration.LoggerConfiguration.CreateLogger()</c>.
///
/// <para>
/// CRIT-FM-G2 confirmed: Layer-1's <c>CreateLogger()</c> returns
/// <c>MMP.Herald.Serilog.ILogger</c> (an interface). This class is a wrapper
/// construction, not a cast.
/// </para>
/// </summary>
public sealed partial class Logger : Serilog.ILogger, IDisposable
{
    // Option 2: hold both the L1.ILogger (always) and the concrete SerilogLoggerAdapter
    // (when available). _adapter is non-null iff the wrapped logger is a SerilogLoggerAdapter.
    // All ILogger forwarding uses _inner. Generated typed overloads use _adapter when non-null
    // for the zero-alloc path, falling through to params when _adapter is null (SilentLogger case).
    private readonly L1.ILogger _inner;
    private readonly L1.SerilogLoggerAdapter? _adapter;

    /// <summary>
    /// Wraps a concrete <see cref="L1.SerilogLoggerAdapter"/>. The typed overloads
    /// generated by <c>SerilogArityGenerator</c> will use this path.
    /// </summary>
    internal Logger(L1.SerilogLoggerAdapter adapter)
    {
        _inner = adapter;
        _adapter = adapter;
    }

    /// <summary>
    /// Wraps any <see cref="L1.ILogger"/> (e.g. <c>SilentLogger.Instance</c>).
    /// When <paramref name="inner"/> is a <see cref="L1.SerilogLoggerAdapter"/> the
    /// typed-overload fast path is still available; otherwise the params fallback is used.
    /// </summary>
    internal Logger(L1.ILogger inner)
    {
        _inner = inner;
        _adapter = inner as L1.SerilogLoggerAdapter;
    }

    /// <summary>
    /// Exposes the concrete adapter for the <c>Serilog.Log</c> setter unwrap.
    /// </summary>
    internal L1.SerilogLoggerAdapter? Adapter => _adapter;

    /// <summary>
    /// Exposes the wrapped L1 logger. Used by <c>Serilog.Log</c> to avoid double-wrap.
    /// </summary>
    internal L1.ILogger Inner => _inner;

    // ── Level gate ────────────────────────────────────────────────────────────
    // ILogger.IsEnabled uses L1Events.LogEventLevel — forward directly, no cast.

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool IsEnabled(L1Events.LogEventLevel level) => _inner.IsEnabled(level);

    // ── Write ─────────────────────────────────────────────────────────────────

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void Write(L1Events.LogEventLevel level, string messageTemplate, params object?[]? propertyValues)
        => _inner.Write(level, messageTemplate, propertyValues);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void Write(L1Events.LogEventLevel level, Exception? exception, string messageTemplate, params object?[]? propertyValues)
        => _inner.Write(level, exception, messageTemplate, propertyValues);

    // ── Verbs (no exception) ──────────────────────────────────────────────────

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void Verbose(string messageTemplate, params object?[]? propertyValues)
        => _inner.Verbose(messageTemplate, propertyValues);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void Debug(string messageTemplate, params object?[]? propertyValues)
        => _inner.Debug(messageTemplate, propertyValues);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void Information(string messageTemplate, params object?[]? propertyValues)
        => _inner.Information(messageTemplate, propertyValues);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void Warning(string messageTemplate, params object?[]? propertyValues)
        => _inner.Warning(messageTemplate, propertyValues);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void Error(string messageTemplate, params object?[]? propertyValues)
        => _inner.Error(messageTemplate, propertyValues);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void Fatal(string messageTemplate, params object?[]? propertyValues)
        => _inner.Fatal(messageTemplate, propertyValues);

    // ── Verbs (with exception) ────────────────────────────────────────────────

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void Verbose(Exception? exception, string messageTemplate, params object?[]? propertyValues)
        => _inner.Verbose(exception, messageTemplate, propertyValues);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void Debug(Exception? exception, string messageTemplate, params object?[]? propertyValues)
        => _inner.Debug(exception, messageTemplate, propertyValues);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void Information(Exception? exception, string messageTemplate, params object?[]? propertyValues)
        => _inner.Information(exception, messageTemplate, propertyValues);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void Warning(Exception? exception, string messageTemplate, params object?[]? propertyValues)
        => _inner.Warning(exception, messageTemplate, propertyValues);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void Error(Exception? exception, string messageTemplate, params object?[]? propertyValues)
        => _inner.Error(exception, messageTemplate, propertyValues);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void Fatal(Exception? exception, string messageTemplate, params object?[]? propertyValues)
        => _inner.Fatal(exception, messageTemplate, propertyValues);

    // ── Context ───────────────────────────────────────────────────────────────

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public Serilog.ILogger ForContext(string propertyName, object? value, bool destructureObjects = false)
        => WrapContext(_inner.ForContext(propertyName, value, destructureObjects));

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public Serilog.ILogger ForContext<TSource>()
        => WrapContext(_inner.ForContext<TSource>());

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public Serilog.ILogger ForContext(Type source)
        => WrapContext(_inner.ForContext(source));

    // ForContext always returns a new SerilogLoggerAdapter (see SerilogLoggerAdapter.cs).
    // The cast is safe; the helper centralises it so a future type change breaks in one place.
    private static Logger WrapContext(L1.ILogger inner)
        => inner is L1.SerilogLoggerAdapter concreteAdapter
            ? new Logger(concreteAdapter)
            : throw new InvalidCastException(
                $"ForContext returned {inner?.GetType().FullName} instead of SerilogLoggerAdapter. " +
                "This is a Herald internal invariant violation.");

    // ── Lifecycle ─────────────────────────────────────────────────────────────

    /// <summary>
    /// Disposes the underlying Herald pipeline if it implements
    /// <see cref="IDisposable"/>. Safe to call multiple times — the
    /// Layer-1 logger owns the idempotency guarantee.
    /// </summary>
    public void Dispose() => (_inner as System.IDisposable)?.Dispose();
}
